use anyhow::Result;

// Generated by `spec build examples/service/units --output examples/service/src/generated`.
mod generated;
pub use generated::*;
pub mod raw_baseline;

fn main() -> Result<()> {
    println!(
        "service example: compare src/raw_baseline/billing/discount_strategy.rs with units/billing/discount_strategy.unit.spec"
    );
    Ok(())
}
