use anyhow::Result;

// Generated by `spec generate units --output src/generated` (or from repo root:
// `cargo run -p spec-cli -- generate examples/ecommerce/units --output examples/ecommerce/src/generated`).
mod generated;
pub use generated::*;
pub mod raw_baseline;

fn main() -> Result<()> {
    println!(
        "ecommerce example: compare src/raw_baseline/pricing/checkout_quote.rs with units/pricing/checkout_quote.unit.spec"
    );
    Ok(())
}
