use anyhow::Result;

// Generated by `spec generate units --output src/generated` (or from repo root:
// `cargo run -p spec-cli -- generate examples/ecommerce/units --output examples/ecommerce/src/generated`).
mod generated;
pub use generated::*;

fn main() -> Result<()> {
    println!("ecommerce example: place generated pricing units under this project");
    Ok(())
}
